// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package net.onrc.onos.core.datastore.serializers;

public final class Device {
  private Device() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DevicePropertyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes mac = 1;
    /**
     * <code>required bytes mac = 1;</code>
     */
    boolean hasMac();
    /**
     * <code>required bytes mac = 1;</code>
     */
    com.google.protobuf.ByteString getMac();

    // repeated bytes portIds = 2;
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPortIdsList();
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    int getPortIdsCount();
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    com.google.protobuf.ByteString getPortIds(int index);

    // optional bytes value = 3;
    /**
     * <code>optional bytes value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code device.DeviceProperty}
   */
  public static final class DeviceProperty extends
      com.google.protobuf.GeneratedMessage
      implements DevicePropertyOrBuilder {
    // Use DeviceProperty.newBuilder() to construct.
    private DeviceProperty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceProperty(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceProperty defaultInstance;
    public static DeviceProperty getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceProperty getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceProperty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mac_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                portIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              portIds_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          portIds_ = java.util.Collections.unmodifiableList(portIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.onrc.onos.core.datastore.serializers.Device.internal_static_device_DeviceProperty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.onrc.onos.core.datastore.serializers.Device.internal_static_device_DeviceProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.class, net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceProperty> PARSER =
        new com.google.protobuf.AbstractParser<DeviceProperty>() {
      public DeviceProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceProperty(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceProperty> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes mac = 1;
    public static final int MAC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>required bytes mac = 1;</code>
     */
    public boolean hasMac() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes mac = 1;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    // repeated bytes portIds = 2;
    public static final int PORTIDS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> portIds_;
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPortIdsList() {
      return portIds_;
    }
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    public int getPortIdsCount() {
      return portIds_.size();
    }
    /**
     * <code>repeated bytes portIds = 2;</code>
     */
    public com.google.protobuf.ByteString getPortIds(int index) {
      return portIds_.get(index);
    }

    // optional bytes value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      mac_ = com.google.protobuf.ByteString.EMPTY;
      portIds_ = java.util.Collections.emptyList();
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, mac_);
      }
      for (int i = 0; i < portIds_.size(); i++) {
        output.writeBytes(2, portIds_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, mac_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < portIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(portIds_.get(i));
        }
        size += dataSize;
        size += 1 * getPortIdsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.onrc.onos.core.datastore.serializers.Device.DeviceProperty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device.DeviceProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.onrc.onos.core.datastore.serializers.Device.DevicePropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.onrc.onos.core.datastore.serializers.Device.internal_static_device_DeviceProperty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.onrc.onos.core.datastore.serializers.Device.internal_static_device_DeviceProperty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.class, net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.Builder.class);
      }

      // Construct using net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        portIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.onrc.onos.core.datastore.serializers.Device.internal_static_device_DeviceProperty_descriptor;
      }

      public net.onrc.onos.core.datastore.serializers.Device.DeviceProperty getDefaultInstanceForType() {
        return net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.getDefaultInstance();
      }

      public net.onrc.onos.core.datastore.serializers.Device.DeviceProperty build() {
        net.onrc.onos.core.datastore.serializers.Device.DeviceProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.onrc.onos.core.datastore.serializers.Device.DeviceProperty buildPartial() {
        net.onrc.onos.core.datastore.serializers.Device.DeviceProperty result = new net.onrc.onos.core.datastore.serializers.Device.DeviceProperty(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mac_ = mac_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          portIds_ = java.util.Collections.unmodifiableList(portIds_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.portIds_ = portIds_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.onrc.onos.core.datastore.serializers.Device.DeviceProperty) {
          return mergeFrom((net.onrc.onos.core.datastore.serializers.Device.DeviceProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.onrc.onos.core.datastore.serializers.Device.DeviceProperty other) {
        if (other == net.onrc.onos.core.datastore.serializers.Device.DeviceProperty.getDefaultInstance()) return this;
        if (other.hasMac()) {
          setMac(other.getMac());
        }
        if (!other.portIds_.isEmpty()) {
          if (portIds_.isEmpty()) {
            portIds_ = other.portIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePortIdsIsMutable();
            portIds_.addAll(other.portIds_);
          }
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMac()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.onrc.onos.core.datastore.serializers.Device.DeviceProperty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.onrc.onos.core.datastore.serializers.Device.DeviceProperty) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes mac = 1;
      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mac = 1;</code>
       */
      public boolean hasMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes mac = 1;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>required bytes mac = 1;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mac = 1;</code>
       */
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }

      // repeated bytes portIds = 2;
      private java.util.List<com.google.protobuf.ByteString> portIds_ = java.util.Collections.emptyList();
      private void ensurePortIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          portIds_ = new java.util.ArrayList<com.google.protobuf.ByteString>(portIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPortIdsList() {
        return java.util.Collections.unmodifiableList(portIds_);
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public int getPortIdsCount() {
        return portIds_.size();
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public com.google.protobuf.ByteString getPortIds(int index) {
        return portIds_.get(index);
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public Builder setPortIds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePortIdsIsMutable();
        portIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public Builder addPortIds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePortIdsIsMutable();
        portIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public Builder addAllPortIds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePortIdsIsMutable();
        super.addAll(values, portIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes portIds = 2;</code>
       */
      public Builder clearPortIds() {
        portIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional bytes value = 3;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:device.DeviceProperty)
    }

    static {
      defaultInstance = new DeviceProperty(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:device.DeviceProperty)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_device_DeviceProperty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_device_DeviceProperty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014device.proto\022\006device\"=\n\016DeviceProperty" +
      "\022\013\n\003mac\030\001 \002(\014\022\017\n\007portIds\030\002 \003(\014\022\r\n\005value\030" +
      "\003 \001(\014B2\n(net.onrc.onos.core.datastore.se" +
      "rializersB\006Device"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_device_DeviceProperty_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_device_DeviceProperty_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_device_DeviceProperty_descriptor,
              new java.lang.String[] { "Mac", "PortIds", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
